---
engines:
  brakeman:
    enabled: true
  bundler_audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-66
  reek:
    enabled: true
    exclude_fingerprints:
      - ec678b5cddf3e42ffa054aca77a4dc65
      - 5b926a8df7748b27151d854c839fd4ae
      - 820b7465c173b6858df11101fe3880ff
