AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
