AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 90

Style/FrozenStringLiteralComment:
  Enabled: false
