language: ruby
rvm:
- 2.3.1
cache: bundle
script: bin/rake
deploy:
  provider: rubygems
  api_key:
    secure: qycHCapF/dwVAMBABf3gHcLkxCMBES0r+pFqLKAiymw4F7q0Nj0Aok6tmO/1VNBvPrbq8tdsZn4ANbIxMMjRA2/2SkMMwatDC0FEB2h77SN0RTXB8kO9ni6o/IU66fYe64KIepc99ls5MyT5xKXeC71TksYO7CdcZiJhg5MmSaygbesFSgOLZJCttsqnM/VePQabDLPfia3xjSey8H3mSRPqptrdjBsG0RNMpy6f32lQFA+f27aYA8GIMkuxaRZjzJ6TDLCs6kAXJpHNf1qTsb393q1Njmymy5Gql07bocfW3iNrra7nAOGUBrCtAv7vWVq9Hq5mY/zmMONL2ugsIMeEOMSYyKYYtTFDqFAMH6MLROVtAFkTfNPyk1diFG/rwbLMSJZz64+eZGOO+foqCYTiqddtVr3Vrf9aE7kO+j86JsUKuhfCd15qolrcxPX0qhSosLw+4h7tb8fwxLAyCiq9luYSTyG2EfTmoLM4kGZf2jrozHiBzFtUXy1gEekZKzmbbebnRpbTymBpZyLTsjuDMu5pegumaAl2P0PYcOTfqOrBw+uM7LDNeJxe75bdOrT3LaAdTZRIoKvdVlhoO3p1r0zMAoEbK0wHtJqkLsYFdvijunMDRWqLFITF1E3kqUPZIpNGoC2NfX4Ej02SvASt82WxIH9OxcaJdgEbX0g=
  gem: presenters
  on:
    tags: true
    repo: tubbo/presenters
addons:
  code_climate:
    repo_token:
      secure: EDzxb1nhZDKbvtTePawKd2hYT+kNAevhQIukB/s/aHei54+9BF7bcF7LTl4V2uIAdBlBj+zFHtR8YvnfsrtTxqMN+Qq9hutQLbqFFbWYLe8KZLGQbUzDLLNyL8iBVLRfF28S0Jr5Ir+QBQlavWZTbCCRdY/6Nk7AIrIRFMIX/ZWEbl5i1vKR7/pLOqvHK0BGiKJVL1k4bDDZM8GvV3s6dNKXrHxQAGKKikYrdegjJMKMyBy5CHfUsZtuQLI/ZKHijK5j0gZxwvqrCGFV3/x6lCfb6F02UUFg9s+Qrxgjq3EKFro+z9cIjFjCotK5j2qaPqhgl0DC+k2IG8N1QCK91IGQdfTCvro99j+wosI9640iU7ioex4Rl8ye+22+U0q0M9QQiwf09+JTl44TguAHs6ht2PTcfwE+fATcGzlIkpaAzT37T3bjgnjiRz2VcFqTwqSvt3/e7uQ0gqQdmbaOWB5x/wqkwDyqz822/BSNOwkdXLy+QIRjUE3DtFOcAK1Y5u7bbdJm8UUzMpxrTsugJEduIxXQHFFfv7ZHvN7imF9QuNhnZh7CZpw9x4unSxsnvY6EDL2Hoc3mRmw3oSipVsO/MVbqu5KJEY6fb+Wwci73v13RPtUWb8xRcWo0FF72WoZAvWG0Yi9bfButqB3j2LeQ55N+XJU84em0UTiqQ/M=
