language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: bin/rake
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: rubygems
  api_key:
    secure: qycHCapF/dwVAMBABf3gHcLkxCMBES0r+pFqLKAiymw4F7q0Nj0Aok6tmO/1VNBvPrbq8tdsZn4ANbIxMMjRA2/2SkMMwatDC0FEB2h77SN0RTXB8kO9ni6o/IU66fYe64KIepc99ls5MyT5xKXeC71TksYO7CdcZiJhg5MmSaygbesFSgOLZJCttsqnM/VePQabDLPfia3xjSey8H3mSRPqptrdjBsG0RNMpy6f32lQFA+f27aYA8GIMkuxaRZjzJ6TDLCs6kAXJpHNf1qTsb393q1Njmymy5Gql07bocfW3iNrra7nAOGUBrCtAv7vWVq9Hq5mY/zmMONL2ugsIMeEOMSYyKYYtTFDqFAMH6MLROVtAFkTfNPyk1diFG/rwbLMSJZz64+eZGOO+foqCYTiqddtVr3Vrf9aE7kO+j86JsUKuhfCd15qolrcxPX0qhSosLw+4h7tb8fwxLAyCiq9luYSTyG2EfTmoLM4kGZf2jrozHiBzFtUXy1gEekZKzmbbebnRpbTymBpZyLTsjuDMu5pegumaAl2P0PYcOTfqOrBw+uM7LDNeJxe75bdOrT3LaAdTZRIoKvdVlhoO3p1r0zMAoEbK0wHtJqkLsYFdvijunMDRWqLFITF1E3kqUPZIpNGoC2NfX4Ej02SvASt82WxIH9OxcaJdgEbX0g=
  gem: makeover
  on:
    tags: true
    repo: tubbo/makeover
env:
  global:
  - COVERAGE=true
  - secure: UxrE/Y54zjbun/mQsjaxj6W7907cablbYks35MWYeNtHG8wuEK0fk2UgXL2hi7LoQUgzJ+7xGLO+U5/8YeQx6GqRKbzxU0omruHQkqYqtGFz0BCssFg4lMHAH/iLotArvcl/oGU4uHooZXDFwUFiggDwb7m5TdD2QK3fVBHG5N8J/FfmzS5Cyf3WfyKhBR0ceotWrAyPUJGC8IKG27YFnsTXg42Mdt6nuIwHSokJXkvTtiFjkE2CBMIfxtZuvPDkch804HkfXpQXb/1sUyWiFL9n20/T3KJDI1dinW4W7svvKqJqTaRoqi1fyrSxbebrIhh3CVdkHw3BFGwLkXfojMlL8sBPEUhB3CHelo0bsXjDP3FxR/vqXihA8llClXc71euCRRiOSNr6ySVtpBfPp/oaH8ZowRNF+Z8C4lV0HDN6XHd561Ap5MadVpLqAdYg1xr+sFcPdI1CRT+soK77zr7j3WrUXJZC5SvWlwxM3Zafqn5SG3suTyJMjuFtVHvlTt+tSvRxHWdptk5QmbXcVuyu2Knd+hTlI7cOhx9vxQXT27ODH5acOtjTvvV9F7KBVHf+fJr1gyJ2HIeoOM18yfiEmsyNj/uk7UbJG7Fj3gIrWo34cXu2xk4J0lu03xx5I81Fig/j5gqi7HaiWkJ1hda6nCyGYdRof0SN1+PGTv0=
